spring:
  application:
    name: PRODUCT-SERVICE
aws:
  region: us-east-1
  dynamodb:
    tableName: BioStockEventsTable

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always